import { useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';

import { RecuadroGlass, Texto } from '../../../diseno';
import { hapticSeguro } from '../../../nucleo/dispositivo/haptics';

type Datos = { alcance: string; disponibilidad: '2' | '4' | '6' | '8'; fecha: string; nivel: 'inicio' | 'basico' | 'intermedio'; objetivo: string; fuente: string };

export function CreadorExamenAby({ onCompletar }: { onCompletar: (datos: Datos) => void }) {
  const [paso, setPaso] = useState(0);
  const [texto, setTexto] = useState('');
  const [datos, setDatos] = useState<Partial<Datos>>({});
  const avanzarTexto = () => { if (!texto.trim()) return; const campo = paso === 0 ? 'objetivo' : paso === 2 ? 'alcance' : 'fuente'; setDatos((actual) => ({ ...actual, [campo]: texto.trim() })); setTexto(''); setPaso((actual) => actual + 1); };
  const elegir = (campo: keyof Datos, valor: string) => { const siguientes = { ...datos, [campo]: valor } as Datos; setDatos(siguientes); if (paso === 4) onCompletar(siguientes); else setPaso((actual) => actual + 1); hapticSeguro('seleccion'); };
  const titulo = ['¿Para qué examen te preparas?', '¿Cuándo es tu examen?', '¿Qué temas entran?', '¿Cuánto tiempo tienes?', '¿Cómo te sientes con el tema?'][paso];
  const textoPaso = paso === 0 || paso === 2;
  return <View style={styles.raiz}><View style={styles.cabecera}><Texto style={styles.sobrelinea}>TU PLAN DE EXAMEN</Texto><Texto style={styles.progreso}>{paso + 1} / 5</Texto></View><Texto style={styles.titulo}>{titulo}</Texto>{textoPaso ? <RecuadroGlass blur intensity={30} style={styles.entrada}><TextInput autoFocus keyboardAppearance="light" onChangeText={setTexto} onSubmitEditing={avanzarTexto} placeholder={paso === 0 ? 'Ej. Parcial de Anatomía I' : 'Ej. Capítulos 1 al 4'} placeholderTextColor="#8C98A6" style={styles.input} value={texto} /><Pressable onPress={avanzarTexto} style={styles.continuar}><Texto style={styles.continuarTexto}>Continuar</Texto></Pressable></RecuadroGlass> : paso === 1 ? <View style={styles.opciones}>{[['Esta semana', '2026-09-11'], ['En 2 semanas', '2026-09-18'], ['En un mes', '2026-10-04']].map(([etiqueta, valor]) => <Pressable key={valor} onPress={() => elegir('fecha', valor)} style={styles.opcion}><Texto style={styles.opcionTexto}>{etiqueta}</Texto></Pressable>)}</View> : paso === 3 ? <View style={styles.opciones}>{['2', '4', '6', '8'].map((valor) => <Pressable key={valor} onPress={() => elegir('disponibilidad', valor)} style={styles.opcion}><Texto style={styles.opcionTexto}>{valor === '8' ? '8 h+' : `${valor} h`}</Texto></Pressable>)}</View> : <View style={styles.opciones}>{[['Estoy empezando', 'inicio'], ['Entiendo lo básico', 'basico'], ['Ya tengo base', 'intermedio']].map(([etiqueta, valor]) => <Pressable key={valor} onPress={() => elegir('nivel', valor)} style={styles.opcion}><Texto style={styles.opcionTexto}>{etiqueta}</Texto></Pressable>)}</View>}</View>;
}

const styles = StyleSheet.create({ cabecera: { flexDirection: 'row', justifyContent: 'space-between' }, continuar: { alignItems: 'center', backgroundColor: '#377DDE', borderRadius: 13, justifyContent: 'center', paddingHorizontal: 13 }, continuarTexto: { color: '#FFF', fontFamily: 'Montserrat-Bold', fontSize: 11 }, entrada: { backgroundColor: 'rgba(255,255,255,0.75)', borderRadius: 18, flexDirection: 'row', padding: 5 }, input: { color: '#293748', flex: 1, fontFamily: 'Montserrat-Medium', fontSize: 12, paddingHorizontal: 10 }, opcion: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.78)', borderColor: 'rgba(55,125,222,0.17)', borderRadius: 16, borderWidth: 1, minHeight: 48, paddingHorizontal: 14, justifyContent: 'center' }, opcionTexto: { color: '#334153', fontFamily: 'Montserrat-Bold', fontSize: 12 }, opciones: { gap: 9 }, progreso: { color: '#377DDE', fontFamily: 'Montserrat-Bold', fontSize: 11 }, raiz: { alignSelf: 'center', gap: 15, width: '84%' }, sobrelinea: { color: '#637282', fontFamily: 'Montserrat-Bold', fontSize: 10, letterSpacing: 1 }, titulo: { color: '#2C3B4C', fontFamily: 'Montserrat-Bold', fontSize: 19, lineHeight: 25 }, });
