import { Pressable, StyleSheet, View } from 'react-native';
import { CheckCircle, MapTrifold } from 'phosphor-react-native';

import { RecuadroGlass, Texto } from '../../../diseno';
import { hapticSeguro } from '../../../nucleo/dispositivo/haptics';
import type { PropuestaSenderoAby as Propuesta } from '../contrato/aby.contrato';

export function PropuestaSenderoAby({ propuesta, onAjustar, onCrear }: { propuesta: Propuesta; onAjustar: () => void; onCrear: () => void }) {
  return <RecuadroGlass blur intensity={28} style={styles.raiz}><View style={styles.cabecera}><View style={styles.icono}><MapTrifold color="#FFFFFF" size={20} weight="fill" /></View><View style={{ flex: 1 }}><Texto style={styles.sobrelinea}>RUTA PROPUESTA</Texto><Texto style={styles.titulo}>{propuesta.titulo}</Texto></View></View><Texto style={styles.descripcion}>{propuesta.descripcion}</Texto><View style={styles.nodos}>{propuesta.nodos.map((nodo, indice) => <View key={nodo.id} style={styles.nodo}><View style={styles.numero}><Texto style={styles.numeroTexto}>{indice + 1}</Texto></View><View style={{ flex: 1 }}><Texto style={styles.nodoTitulo}>{nodo.titulo}</Texto><Texto style={styles.nodoMeta}>{nodo.actionPack.widgets.length} herramienta{nodo.actionPack.widgets.length === 1 ? '' : 's'}</Texto></View></View>)}</View><View style={styles.acciones}><Pressable accessibilityRole="button" onPress={() => { hapticSeguro('seleccion'); onAjustar(); }} style={styles.ajustar}><Texto style={styles.ajustarTexto}>Ajustar</Texto></Pressable><Pressable accessibilityRole="button" onPress={() => { hapticSeguro('confirmacion'); onCrear(); }} style={styles.crear}><CheckCircle color="#FFFFFF" size={19} weight="fill" /><Texto style={styles.crearTexto}>Crear mi sendero</Texto></Pressable></View></RecuadroGlass>;
}

const styles = StyleSheet.create({
  acciones: { flexDirection: 'row', gap: 9, marginTop: 3 }, ajustar: { alignItems: 'center', borderColor: 'rgba(91,46,145,0.17)', borderRadius: 15, borderWidth: 1, justifyContent: 'center', paddingHorizontal: 15 }, ajustarTexto: { color: '#5B2E91', fontFamily: 'MontserratAlternates-Bold', fontSize: 12 }, cabecera: { alignItems: 'center', flexDirection: 'row', gap: 10 }, crear: { alignItems: 'center', backgroundColor: '#5B2E91', borderRadius: 15, flex: 1, flexDirection: 'row', gap: 7, justifyContent: 'center', minHeight: 45 }, crearTexto: { color: '#FFFFFF', fontFamily: 'MontserratAlternates-Bold', fontSize: 12 }, descripcion: { color: '#62576B', fontFamily: 'MontserratAlternates-Medium', fontSize: 12, lineHeight: 18 }, icono: { alignItems: 'center', backgroundColor: '#7B4BB2', borderRadius: 15, height: 40, justifyContent: 'center', width: 40 }, nodo: { alignItems: 'center', flexDirection: 'row', gap: 9 }, nodoMeta: { color: '#8D8193', fontFamily: 'MontserratAlternates-Medium', fontSize: 10, marginTop: 2 }, nodoTitulo: { color: '#4A3B55', fontFamily: 'MontserratAlternates-Bold', fontSize: 12 }, nodos: { gap: 10 }, numero: { alignItems: 'center', backgroundColor: 'rgba(91,46,145,0.11)', borderRadius: 12, height: 25, justifyContent: 'center', width: 25 }, numeroTexto: { color: '#5B2E91', fontFamily: 'MontserratAlternates-Bold', fontSize: 11 }, raiz: { backgroundColor: 'rgba(255,255,255,0.76)', borderColor: 'rgba(91,46,145,0.18)', borderRadius: 25, borderWidth: 1, gap: 13, padding: 16 }, sobrelinea: { color: '#76539C', fontFamily: 'MontserratAlternates-Bold', fontSize: 10, letterSpacing: 1 }, titulo: { color: '#3F3248', fontFamily: 'MontserratAlternates-Bold', fontSize: 16, marginTop: 2 },
});
