import { ArrowLeft, Check, Circle, Play, Sparkles } from 'lucide-react-native';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import Svg, { Polygon } from 'react-native-svg';
import { RecuadroGlass, Texto, colores } from '../../../diseno';
import { hapticSeguro } from '../../../nucleo/dispositivo/haptics';

export function EspacioTrabajoSendero({ sendero, color, onCerrar }: { sendero: { descripcion: string; titulo: string }; color: string; onCerrar: () => void }) {
  const [paso, setPaso] = useState(0);
  const pasos = ['Preparar', 'Avanzar', 'Cerrar'];
  return <RecuadroGlass blur intensity={68} style={s.root}><View style={s.head}><Pressable onPress={onCerrar} style={s.back}><ArrowLeft color={colores.texto} size={18}/></Pressable><View style={{flex:1}}><Texto style={s.eyebrow}>ESPACIO DE TRABAJO</Texto><Texto style={s.title}>{sendero.titulo}</Texto></View></View><View style={s.rail}><View style={[s.line,{backgroundColor:color}]}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.railContent}>{pasos.map((nombre,i)=>{const activo=i===paso, hecho=i<paso, Icono=hecho?Check:activo?Sparkles:Circle;return <Pressable key={nombre} onPress={()=>i<=paso&&setPaso(i)} style={s.step}><View style={s.star}><Svg width={58} height={58} viewBox="0 0 100 100"><Polygon points="50,3 66,38 97,43 73,65 79,96 50,78 21,96 27,65 3,43 34,38" fill={hecho||activo?color:'#BDBDBD'}/></Svg><View style={s.starIcon}><Icono color="#fff" size={20}/></View></View><Texto style={[s.stepText,activo&&{color}]}>{nombre}</Texto></Pressable>})}</ScrollView></View><View style={s.action}><Texto style={s.eyebrow}>PASO {paso+1} DE {pasos.length}</Texto><Texto style={s.actionTitle}>{pasos[paso]}</Texto><Texto style={s.desc}>{sendero.descripcion}</Texto><Pressable onPress={()=>{hapticSeguro('accion');setPaso(v=>Math.min(v+1,pasos.length-1));}} style={[s.button,{backgroundColor:color}]}><Play color="#fff" fill="#fff" size={16}/><Texto style={s.buttonText}>Completar paso</Texto></Pressable></View></RecuadroGlass>;
}
const s=StyleSheet.create({root:{borderRadius:26,gap:16,padding:16},head:{alignItems:'center',flexDirection:'row',gap:10},back:{alignItems:'center',backgroundColor:'rgba(255,255,255,.7)',borderRadius:14,height:36,justifyContent:'center',width:36},eyebrow:{color:colores.textoSecundario,fontFamily:'MontserratAlternates-Bold',fontSize:9,letterSpacing:.7},title:{color:colores.texto,fontFamily:'MontserratAlternates-Bold',fontSize:20},rail:{height:92,position:'relative'},line:{height:2,left:24,opacity:.3,position:'absolute',right:24,top:29},railContent:{gap:12,paddingHorizontal:8},step:{alignItems:'center',gap:4,width:72},star:{height:58,position:'relative',width:58},starIcon:{alignItems:'center',bottom:0,justifyContent:'center',left:0,position:'absolute',right:0,top:0},stepText:{color:colores.textoSecundario,fontFamily:'MontserratAlternates-Bold',fontSize:9},action:{backgroundColor:'rgba(255,255,255,.45)',borderRadius:20,gap:8,padding:16},actionTitle:{color:colores.texto,fontFamily:'MontserratAlternates-Bold',fontSize:20},desc:{color:colores.textoSecundario,fontFamily:'MontserratAlternates-SemiBold',fontSize:12,lineHeight:17},button:{alignItems:'center',borderRadius:16,flexDirection:'row',gap:8,justifyContent:'center',marginTop:4,minHeight:50},buttonText:{color:'#fff',fontFamily:'MontserratAlternates-Bold'}});
